version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: ./
          ignore-rules: 'DL4005,DL3008'
          trusted-registries: 'docker.io'
